config/routes.rb
Rails.application.routes.draw do
  #root :to => "students#index_with_results"
  root :to => "application#my_root"

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get 'users/sign_in', to: 'users/sessions#new', as: :new_user_session
    get 'users/sign_out', to: 'users/sessions#destroy', as: :destroy_user_session
  end

  get 'student_page', to: 'student_page#main'
  get 'student_page/results_for_batch', to: 'student_page#results_for_batch'

  resources :admins, only: [:index] do
    collection do
      get :update_gripau_data
      get :execute_all_tests
      get :import_students
      get :careful_gripau_console_page
      get :careful_upgrade_gripau
      get :careful_view_logs
      get :login_as
    end
  end
  

  resources :teachers do
    collection do
      get :update_gripau_data
    end
  end
  resources :exercice_groups
  resources :exercice_batches do
    collection do
      get :import
    end
    member do
      get :make_public
      get :student_results
      get :student_results_resumee
      get :execute_tests
      get :exercices_stats
      get :export_student_solutions
    end
  end

  resources :test_executions
  resources :test_case_executions do
    member do
      get :manual_accept
    end
  end
  resources :check_style_failures
  resources :test_failures
  resources :test_case_executions
  resources :exercice_tests_executions
  
  resources :student_repositories do
    member do
      get :validate
    end
  end

  resources :student_submissions do
    member do
      get :execute_tests
    end
    collection do
      get :import
      post :do_import
    end
  end

  resources :test_cases
  resources :exercices do
    member do
      get :find_exercice_code
    end
  end

  resources :students do 
    collection do
      get :index_with_results
      get :import
      post :do_import
      get :dashboard
    end
    member do 
      get :edit_git_url
      patch :update_git_url
      get :student_page
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/student.rb
class Student < ApplicationRecord
  has_one :user
	belongs_to :teacher
	has_many :student_repositories
  has_many :student_submissions
	has_many :test_executions, through: :student_submissions, source: "test_executions"
  has_many :manual_test_case_validations

  def teacher?
  	false
  end

  def student?
  	true
  end

  def default_repository
    student_repositories.last
  end

  def repositories
    student_repositories
  end

  def change_all_repo_urls url
    update!(git_url: url)
    student_repositories.update_all(git_url: url)
    ## TODO: clear caches!
  end

  def course
  	teacher_id == 3 ? "daw" : "dam"
  end

	def main_package
		"cat.itb.#{username.gsub(".", "").gsub("-", "")}.#{course}"
	end

	def self.import_all
		Teacher.all.each do |teacher|
      extension = teacher.email.split("@")[0]
      file = File.new("../gripau-data/students_#{extension}.csv")
      Student.import_csv(teacher, file)  
    end
     
    ExerciceBatch.all.each do |exercice_batch|
      if !StudentSubmission.where(exercice_batch: exercice_batch).exists?
        StudentSubmission.create_all_for(exercice_batch.id)
      end
    end
	end

	def self.import_csv(teacher, file)
		require 'csv'
		CSV.foreach(file.path, headers: false) do |row|
			full_name = row[0]
			email = row[1]
			git_url = row[2]

			next if Student.exists?(teacher: teacher, email: email)
			
			name = full_name.split(",")[1]
			surnames = full_name.split(",")[0]
      username = email.split("@")[0]
      student = Student.create!(teacher: teacher, username: username, name: name, surnames:surnames, email: email)
      StudentRepository.create!(student: student, git_url: git_url)
	  end
	end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :teacher_required!
  before_action :set_student, only: [:show, :edit, :update, :destroy, :student_page, :edit_git_url, :update_git_url]
  
  def dashboard
    @exercice_batches = ExerciceBatch.all
  end

  # GET /students
  # GET /students.json
  def index
    @students = teacher_students
  end

  def index_with_results
    if params[:all]
      @students = Student.all
    else
      @students = teacher_students
    end
  end

  def import
  end

  def do_import
    Student.import_csv(current_teacher, params[:file])
    redirect_to students_path, notice: "Students imported"
  end

  def student_page
    @simulated_user = User.new(student: @student)
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end


  def edit_git_url
  end

  def update_git_url
    @student.change_all_repo_urls(student_params[:git_url])
    redirect_to @student, notice: 'Student was successfully updated.'
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:username, :name, :surnames, :email, :git_url)
    end

    def teacher_students
      current_teacher.students
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_with(model: student, local: true) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :surnames %>
    <%= form.text_field :surnames %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>


  <div class="field">
    <%= form.label :git_url %>
    <%= form.text_field :git_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/students/_show_student_atts.html.erb
<p>
  <strong>Username:</strong>
  <%= student.username %>
</p>

<p>
  <strong>Name:</strong>
  <%= student.name %>
</p>

<p>
  <strong>Surnames:</strong>
  <%= student.surnames %>
</p>

<p>
  <strong>Email:</strong>
  <%= student.email %>
</p>

app/views/students/_student_full_data.erb
<%= render partial: student, layout: "students/show_student_atts"%>

<%= render partial: student, layout: "students/submissions_table"%>

<%= render partial: student, layout: "students/repositories_table"%>


<h3>Results</h3>
<%= render partial: student, layout: "students/results_resumee_table"%>

<%= render partial: student, layout: "students/test_executions_table"%>

<%= render partial: student, layout: "students/test_executions_details_table"%>


  

app/views/students/_submissions_table.html.erb
<h3>Submissions</h3>
<table class="table table-striped">
  <tbody>
    <% student.student_submissions.each do |student_submission| %>
      <tr>
        <%= render student_submission %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/students/_test_executions_details_table.html.erb
<h3>Test executions details</h3>
<div data-controller="test-execution">
  <%if current_teacher %>
  <div class="btn btn-primary" data-action="click->test-execution#toggleCheckStyleView">View checkstyle</div>
  <div class="btn btn-primary" data-action="click->test-execution#toggleSourceCodeView">View sources</div>
  <% end %>
  <div data-test-execution-target="resultDetailContainer" class="hide-sources hide-check-style">
  <% student.student_submissions.each do |student_submission| %>
    <h4><%= student_submission.exercice_batch.name %></h4>
    <% test_execution = student_submission.test_execution %>
    <% @test_execution = test_execution%>
    <% if test_execution %>
      <%= render partial: test_execution, layout: "test_executions/test_execution_with_data"%>
    <% end %>
  <% end %>
</div>
  
</div>

app/views/students/dashboard.html.erb
<h1>Importers</h1>
<ul>
	<li><%= link_to 'Students', students_path %></li>
	<li><%= link_to 'Repositories', student_repositories_path %></li>
  <li><%= link_to 'Submissions', student_submissions_path %></li>
</ul>

<h1>Results</h1>
<ul>
	<li><%= link_to 'Exercice Batches', exercice_batches_path %></li>
</ul>


<!--h1>Executors</h1>
<%#= form_tag do_import_student_repositories_path, multipart: true do %>
	<%#= select_tag :exercice_batch_id,  options_from_collection_for_select(@exercice_batches, "id", "name")%><br>
	<%#= submit_tag "Import csv" %><br>
<%# end %>
-->

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/edit_git_url.html.erb
<% student= @student%>
<%= form_with(model: student, local: true, url: update_git_url_student_path(student)) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :git_url %>
    <%= form.text_field :git_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/students/import.html.erb
<h1>Import CSV</h1>
Select CSV with two columns: student full name and email
<%= form_tag do_import_students_path, multipart: true do %>
	<%= file_field_tag :file %>
	<%= submit_tag "Import csv" %>
<% end %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Students</h1>



<table class="table table-striped">
  <thead>
    <tr>
      <th>Username</th>
      <th>Name</th>
      <th>Surnames</th>
      <th>Email</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.username %></td>
        <td><%= student.name %></td>
        <td><%= student.surnames %></td>
        <td><%= student.email %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Edit git url', edit_git_url_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>
<%= link_to 'Import students', import_students_path %>

app/views/students/index_with_results.html.erb
<p id="notice"><%= notice %></p>

<h1>Students</h1>


<% @students.each do |student| %>
<div class="student_data">
  <h4>
    <%= link_to student.email, student %>
  </h4>

  <%= render partial: student, layout: "students/results_resumee_table"%>
    
  <%# @test_execution = student.test_executions.last %>
  <%# if @test_execution %>
    <%#= render partial: @test_execution, layout: "test_executions/test_execution_with_data"%>
  <%# end %>
</div>
<% end %>
  

app/views/students/show.html.erb
<%= render partial: @student, layout: "students/student_full_data"%>

app/views/students/student_page.html.erb
<%= render partial: @student, layout: "students/show_student_atts"%>

<%=render partial: @student, layout: "student_page/student_page"%>