config/routes.rb
Rails.application.routes.draw do
  #root :to => "students#index_with_results"
  root :to => "application#my_root"

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get 'users/sign_in', to: 'users/sessions#new', as: :new_user_session
    get 'users/sign_out', to: 'users/sessions#destroy', as: :destroy_user_session
  end

  get 'student_page', to: 'student_page#main'
  get 'student_page/results_for_batch', to: 'student_page#results_for_batch'

  resources :admins, only: [:index] do
    collection do
      get :update_gripau_data
      get :execute_all_tests
      get :import_students
      get :careful_gripau_console_page
      get :careful_upgrade_gripau
      get :careful_view_logs
      get :login_as
    end
  end
  

  resources :teachers do
    collection do
      get :update_gripau_data
    end
  end
  resources :exercice_groups
  resources :exercice_batches do
    collection do
      get :import
    end
    member do
      get :make_public
      get :student_results
      get :student_results_resumee
      get :execute_tests
      get :exercices_stats
      get :export_student_solutions
    end
  end

  resources :test_executions
  resources :test_case_executions do
    member do
      get :manual_accept
    end
  end
  resources :check_style_failures
  resources :test_failures
  resources :test_case_executions
  resources :exercice_tests_executions
  
  resources :student_repositories do
    member do
      get :validate
    end
  end

  resources :student_submissions do
    member do
      get :execute_tests
    end
    collection do
      get :import
      post :do_import
    end
  end

  resources :test_cases
  resources :exercices do
    member do
      get :find_exercice_code
    end
  end

  resources :students do 
    collection do
      get :index_with_results
      get :import
      post :do_import
      get :dashboard
    end
    member do 
      get :edit_git_url
      patch :update_git_url
      get :student_page
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/exercice_batch.rb
class ExerciceBatch < ApplicationRecord
	enum results_visivility: { private: 0, public_resumee: 1, public_details: 2 }, _prefix: :results_visivility

	has_many :exercice_groups
	has_many :student_submissions

	def self.addAllStudentsToAllBatches
	  ExerciceBatch.all.each do |exercice_batch|
         StudentSubmission.create_all_for(exercice_batch.id)
      end
	end

	def self.import_yml(file)
		require 'yaml'
		batch_datas = YAML.load_file(file)
		batch_datas.each do |batch_data|
			batch = ExerciceBatch.where(name: batch_data["name"]).first_or_initialize
			batch.data_path = batch_data["data_path"]
			batch.git_tag = batch_data["git_tag"]
			batch.results_visivility = batch_data["secret_results"] ? "private" : "public_resumee"
			batch.save
		end
		ExerciceBatch.addAllStudentsToAllBatches
	end

	def export_student_solutions teacher
		folder = "tmp/export/#{self.id}"
	    `rm -rf #{folder}`
	    `mkdir -p #{folder}/src`
	    
	    self.student_submissions.each do |student_submission|
	      next unless student_submission.teacher == teacher
	      dest_folder = TestJobExecutor.dest_folder_for_repo student_submission.student, self
	      `cp #{dest_folder}/src/* #{folder}/src -r`
	    end
	    result = "#{self.id}.tar.gz"
	    `cd tmp/export/ && tar czf #{result} #{self.id}`
	    result
	end
end

app/controllers/exercice_batches_controller.rb
class ExerciceBatchesController < ApplicationController
  before_action :teacher_required!
  before_action :set_exercice_batch, only: [:show, :edit, :update, :destroy, :student_results, :execute_tests, :exercices_stats, :export_student_solutions, :student_results_resumee, :make_public]

  # GET /exercice_batches
  # GET /exercice_batches.json
  def index
    @exercice_batches = ExerciceBatch.all
  end

  # GET /exercice_batches/1
  # GET /exercice_batches/1.json
  def show
  end

  def export_student_solutions
    file = @exercice_batch.export_student_solutions(current_teacher)
    result = Rails.root.join("tmp/export/#{file}")
    send_file(result.to_s,:filename => "sources.tar.gz",:type => "mime/type")
  end

  def exercices_stats
    @student_submissions =  @exercice_batch.student_submissions.for_teacher current_teacher
  end

  def student_results
    @student_submissions =  @exercice_batch.student_submissions.for_teacher current_teacher
  end

  def student_results_resumee
    @student_submissions =  @exercice_batch.student_submissions.for_teacher current_teacher
  end

  def execute_tests
    force =  params[:force_test]
    ExecuteExerciceBatchTestJob.perform_later @exercice_batch, current_teacher, force
  end

  def make_public
    @exercice_batch.results_visivility_public_details!
    redirect_to action: "index"  
  end

  # GET /exercice_batches/new
  def new
    @exercice_batch = ExerciceBatch.new
  end

  def import
    ExerciceBatch.import_yml("../gripau-data/exercice_batches.yml")
    redirect_to action: "index"
  end

  # GET /exercice_batches/1/edit
  def edit
  end

  # POST /exercice_batches
  # POST /exercice_batches.json
  def create
    @exercice_batch = ExerciceBatch.new(exercice_batch_params)
    saved = @exercice_batch.save
    StudentRepository.create_all_for(@exercice_batch.id) if saved

    respond_to do |format|
      if @exercice_batch.save
        format.html { redirect_to @exercice_batch, notice: 'Exercice batch was successfully created.' }
        format.json { render :show, status: :created, location: @exercice_batch }
      else
        format.html { render :new }
        format.json { render json: @exercice_batch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exercice_batches/1
  # PATCH/PUT /exercice_batches/1.json
  def update
    respond_to do |format|
      if @exercice_batch.update(exercice_batch_params)
        format.html { redirect_to @exercice_batch, notice: 'Exercice batch was successfully updated.' }
        format.json { render :show, status: :ok, location: @exercice_batch }
      else
        format.html { render :edit }
        format.json { render json: @exercice_batch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exercice_batches/1
  # DELETE /exercice_batches/1.json
  def destroy
    @exercice_batch.destroy
    respond_to do |format|
      format.html { redirect_to exercice_batches_url, notice: 'Exercice batch was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exercice_batch
      @exercice_batch = ExerciceBatch.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def exercice_batch_params
      params.require(:exercice_batch).permit(:name, :subpackage, :git_tag, :results_visivility)
    end
end

app/helpers/exercice_batches_helper.rb
module ExerciceBatchesHelper
end

app/views/exercice_batches/_exercice_batch_for_student.html.erb
<%= turbo_frame_tag dom_id_for_records(exercice_batch, student) do %>
  <% @test_execution = student.test_executions.where(exercice_batch: exercice_batch).last %>
  <h4 class="student-id">
    <%= student.email %>
  </h4>
  <% if @test_execution %>
    <%= render partial: @test_execution, layout: "test_executions/test_execution_with_data"%>
  <% end %>
<% end %>

app/views/exercice_batches/_form.html.erb
<%= simple_form_for(exercice_batch) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :data_path %>
    <%= f.input :git_tag %>


  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/exercice_batches/edit.html.erb
<h1>Editing Exercice Batch</h1>

<%= render 'form', exercice_batch: @exercice_batch %>

<%= link_to 'Show', @exercice_batch %> |
<%= link_to 'Back', exercice_batches_path %>

app/views/exercice_batches/execute_tests.html.erb
<div class="text-center">
	    <h1 class="cover-heading">Testing</h1>
	    <p class="lead">Gripau is processing bugs. May take a while.</p>
	    <%= image_tag("frog_eating_bug.gif", :alt => "waiting") %>
	</main>
</div>

app/views/exercice_batches/exercices_stats.html.erb
<h1><%= @exercice_batch.name %></h1>

<div class="exercice-batch-student-results">
<div data-controller="test-execution">
  <div class="btn btn-primary" data-action="click->test-execution#toggleDetailsView">Hide details</div>
  <div class="btn btn-primary" data-action="click->test-execution#toggleCheckStyleView">View checkstyle</div>

<% exercice_sucess = {}
exercice_fails = {}
@student_submissions.each do |student_submission| 
	test_execution = student_submission.test_execution
	next unless test_execution
	test_execution.exercice_tests_executions.each do |exercice_tests_execution|
		exercice = exercice_tests_execution.exercice 
		if exercice_tests_execution.source_found
			if exercice_tests_execution.success?
				exercice_sucess[exercice.id] = (exercice_sucess[exercice.id] || 0) + 1
			else
				exercice_fails[exercice.id] = (exercice_fails[exercice.id] || 0) + 1
			end
		end 
	end 
end %>

<table class="table">
<% @exercice_batch.exercice_groups.each do |exercice_group| %>
	<% exercice_group.exercices.each do |exercice| %>
		<tr>
			<td class="exercice-name"><%= exercice.class_name %></td>
			<td>
		<% success = exercice_sucess[exercice.id] || 0 %>
		<% failures = exercice_fails[exercice.id] || 0 %>
		<%= render "components/progress_bar", total: @student_repositories.count, valid: success, invalid: failures %></td>
		</tr>
	<% end %>
<% end %>
</table>

app/views/exercice_batches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Exercice Batches</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Visivility</th>
      <th colspan="7"></th>
    </tr>
  </thead>

  <tbody>
    <% @exercice_batches.each do |exercice_batch| %>
      <tr>
        <td><%= exercice_batch.name %></td>
        <td><%= exercice_batch.results_visivility %></td>
        <td><%= link_to 'Results', student_results_exercice_batch_path(exercice_batch) %></td>
        <td><%= link_to 'Result resumee', student_results_resumee_exercice_batch_path(exercice_batch) %></td>
        <td><%= link_to 'Exercice Stats', exercices_stats_exercice_batch_path(exercice_batch) %></td>
        <td><%= link_to 'Execute', execute_tests_exercice_batch_path(exercice_batch) %></td>
        <td><%= link_to 'Execute FORCED', execute_tests_exercice_batch_path(exercice_batch, force_test: true) %></td>
        <td><%= link_to 'Export sources', export_student_solutions_exercice_batch_path(exercice_batch) %></td>
        <td><%= link_to "Export CSV", student_results_exercice_batch_path(exercice_batch, {:format => :csv }) %></td>
        
        <td><%= link_to 'Make Public', make_public_exercice_batch_path(exercice_batch) %></td>
        <!--td><%= link_to 'Show', exercice_batch %></td>
        <td><%= link_to 'Edit', edit_exercice_batch_path(exercice_batch) %></td>
        <td><%= link_to 'Destroy', exercice_batch, method: :delete, data: { confirm: 'Are you sure?' } %></td-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Import from gripau-data', import_exercice_batches_path %>
<br>

<%= link_to 'New Exercice Batch', new_exercice_batch_path %>

app/views/exercice_batches/new.html.erb
<h1>New Exercice Batch</h1>

<%= render 'form', exercice_batch: @exercice_batch %>

<%= link_to 'Back', exercice_batches_path %>

app/views/exercice_batches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @exercice_batch.name %>
</p>


<%= link_to 'Edit', edit_exercice_batch_path(@exercice_batch) %> |
<%= link_to 'Back', exercice_batches_path %> | 

<%= link_to 'Test', execute_tests_exercice_batch_path(@exercice_batch) %>

app/views/exercice_batches/student_results.csv.erb
<%

require 'csv'
header = ["Email"]
subheader = [nil]
@exercice_batch.exercice_groups.first.exercices.each do |exercice|
  header << exercice.class_name
  header += Array.new(exercice.test_cases.count, nil)
  subheader << "checkstyle"
  exercice.test_cases.each do |test_case|
    subheader << test_case.name
  end
end
%><%= CSV.generate_line header %><%= CSV.generate_line subheader %><%
@student_submissions.each do |student_submission|

  student_row = []
  student = student_submission.student

  student_row << student.email

  test_execution = student.test_executions.where(exercice_batch: @exercice_batch).last
  next unless test_execution
  @exercice_batch.exercice_groups.first.exercices.each do |exercice|
    exercice_tests_execution = test_execution.exercice_tests_executions.find_by(exercice: exercice)
    if !exercice_tests_execution || !exercice_tests_execution.source_found
      cols = exercice.test_cases.count+1
      student_row += Array.new(cols, nil)
    else
      if exercice_tests_execution.check_style_failure.empty?
        student_row << nil
      else
        student_row << exercice_tests_execution.check_style_failure.all.map{|x| x.message}.join(". ")
      end
      
      exercice.test_cases.each do |test_case|
        test_case_execution = exercice_tests_execution.test_case_executions.find_by(test_case: test_case)
        student_row << ((test_case_execution && !test_case_execution.failed?) ? 1 : 0)
      end
    end
  end

  %><%= CSV.generate_line student_row %><% end %>

  

app/views/exercice_batches/student_results.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @exercice_batch.name %></h1>

<div class="exercice-batch-student-results">
<div data-controller="test-execution">
  <div class="btn btn-primary" data-action="click->test-execution#toggleCheckStyleView">View checkstyle</div>
  <div class="btn btn-primary" data-action="click->test-execution#toggleSourceCodeView">View sources</div>
  <%= link_to "Export CSV", {:format => :csv }, class: "btn btn-primary" %>

<div data-test-execution-target="resultDetailContainer" class="hide-sources hide-check-style">
  <% @student_submissions.each do |student_submission| %>
  	<% student = student_submission.student %>
  	<%= render partial: "exercice_batch_for_student", locals: {student: student, exercice_batch: @exercice_batch} %>
  <% end %>
</div>

</div>
</div>

app/views/exercice_batches/student_results_resumee.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @exercice_batch.name %></h1>

<div class="exercice-batch-student-results">
<div data-controller="test-execution">
  <div class="btn btn-primary" data-action="click->test-execution#toggleDetailsView">Hide details</div>
  <div class="btn btn-primary" data-action="click->test-execution#toggleCheckStyleView">View checkstyle</div>


<table class="table table-striped">
  <tbody>
<% @student_submissions.each do |student_submission| %>
  <% student = student_submission.student %>
  <tr>
    <td class="exercice_batch_name"><%= student.email %></td>
    <td>
      <% test_execution = student_submission.test_execution %>
      <% if test_execution %>
        <%= render partial: test_execution, layout: "test_executions/result_resumee", locals: {user: current_user}%>
      <% else %>
        <span class="badge badge-danger badge-pill">Never run</span>
      <% end %>
    </td>
    <td style="width: 0px">
      <%= link_to "TestAgain", execute_tests_student_submission_path(student_submission) %>
    </td>
  </tr>
<% end %>

</div>
</div>