config/routes.rb
Rails.application.routes.draw do
  #root :to => "students#index_with_results"
  root :to => "application#my_root"

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get 'users/sign_in', to: 'users/sessions#new', as: :new_user_session
    get 'users/sign_out', to: 'users/sessions#destroy', as: :destroy_user_session
  end

  get 'student_page', to: 'student_page#main'
  get 'student_page/results_for_batch', to: 'student_page#results_for_batch'

  resources :admins, only: [:index] do
    collection do
      get :update_gripau_data
      get :execute_all_tests
      get :import_students
      get :careful_gripau_console_page
      get :careful_upgrade_gripau
      get :careful_view_logs
      get :login_as
    end
  end
  

  resources :teachers do
    collection do
      get :update_gripau_data
    end
  end
  resources :exercice_groups
  resources :exercice_batches do
    collection do
      get :import
    end
    member do
      get :make_public
      get :student_results
      get :student_results_resumee
      get :execute_tests
      get :exercices_stats
      get :export_student_solutions
    end
  end

  resources :test_executions
  resources :test_case_executions do
    member do
      get :manual_accept
    end
  end
  resources :check_style_failures
  resources :test_failures
  resources :test_case_executions
  resources :exercice_tests_executions
  
  resources :student_repositories do
    member do
      get :validate
    end
  end

  resources :student_submissions do
    member do
      get :execute_tests
    end
    collection do
      get :import
      post :do_import
    end
  end

  resources :test_cases
  resources :exercices do
    member do
      get :find_exercice_code
    end
  end

  resources :students do 
    collection do
      get :index_with_results
      get :import
      post :do_import
      get :dashboard
    end
    member do 
      get :edit_git_url
      patch :update_git_url
      get :student_page
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/test_execution.rb
class TestExecution < ApplicationRecord
  enum repository_status: { working: 0, tag_not_found: -1, not_found: -2 }, _prefix: :repository

  belongs_to :student_submission
  belongs_to :exercice_batch
  has_many :exercice_tests_executions
  has_one :student, through: :student_submission
  has_one_attached :test_report_file

  scope :last_first, -> { order("created_at DESC") }

  after_save do
    student_submission.update(test_execution: self)
  end

  def resumee
  	total_count = exercice_tests_executions.count
  	not_found_count = exercice_tests_executions.where(source_found: false).count
  	 #failed_count = exercice_tests_executions.joins(test_case_executions: [:test_failures]).distinct("exercice_tests_executions.id").count

    failed_count = exercice_tests_executions.sum do |exercice_tests_execution|
      failed = exercice_tests_execution.test_case_executions.any? do |test_case_execution|
        test_case_execution.failed?
      end
      failed ? 1 : 0
    end
    

  	correct_count = total_count - (not_found_count + failed_count)
  	return {total_count: total_count, not_found_count: not_found_count, failed_count: failed_count, correct_count: correct_count}
  end

  def sources_found?
    exercice_tests_executions.where(source_found: true).exists?
  end

  def tests_available?
    compile_success && sources_found?
  end

  def results_visible_for? user
    !exercice_batch.results_visivility_private? || (user.is_a?(User) && user.teacher?)
  end

end

app/controllers/test_executions_controller.rb
class TestExecutionsController < ApplicationController
  before_action :teacher_required!
  before_action :set_test_execution, only: [:show, :edit, :update, :destroy]

  # GET /test_executions
  # GET /test_executions.json
  def index
    @test_executions = TestExecution.all
  end

  # GET /test_executions/1
  # GET /test_executions/1.json
  def show
    @exercice_test_executions = ExerciceTestsExecution.where(test_execution: @test_execution).includes(:check_style_failure, test_case_executions: [:test_failures])

  end

  # GET /test_executions/new
  def new
    @test_execution = TestExecution.new
  end

  # GET /test_executions/1/edit
  def edit
  end

  # POST /test_executions
  # POST /test_executions.json
  def create
    @test_execution = TestExecution.new(test_execution_params)

    respond_to do |format|
      if @test_execution.save
        format.html { redirect_to @test_execution, notice: 'Test execution was successfully created.' }
        format.json { render :show, status: :created, location: @test_execution }
      else
        format.html { render :new }
        format.json { render json: @test_execution.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /test_executions/1
  # PATCH/PUT /test_executions/1.json
  def update
    respond_to do |format|
      if @test_execution.update(test_execution_params)
        format.html { redirect_to @test_execution, notice: 'Test execution was successfully updated.' }
        format.json { render :show, status: :ok, location: @test_execution }
      else
        format.html { render :edit }
        format.json { render json: @test_execution.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /test_executions/1
  # DELETE /test_executions/1.json
  def destroy
    @test_execution.destroy
    respond_to do |format|
      format.html { redirect_to test_executions_url, notice: 'Test execution was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_test_execution
      @test_execution = TestExecution.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def test_execution_params
      params.require(:test_execution).permit(:student_id, :exercice_batch_id, :date)
    end
end

app/helpers/test_executions_helper.rb
module TestExecutionsHelper
  def repository_status_as_text test_execution
    if test_execution.repository_working?
      "Working"
    elsif test_execution.repository_tag_not_found?
      "Tag not found"
    elsif test_execution.repository_not_found?
      "Repository not found"
    else
      throw "Invalid option"
    end
    
  end
end

app/views/test_executions/_compile_badge.html.erb
<% if test_execution.repository_working? and !test_execution.compile_success%>
	<span class="badge badge-danger badge-pill"  data-bs-toggle="tooltip" data-bs-placement="top" title="<%= test_execution.command_output %>">Compilation failed</span>
<% end %>

app/views/test_executions/_form.html.erb
<%= form_with(model: test_execution, local: true) do |form| %>
  <% if test_execution.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(test_execution.errors.count, "error") %> prohibited this test_execution from being saved:</h2>

      <ul>
        <% test_execution.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :student_id %>
    <%= form.text_field :student_id %>
  </div>

  <div class="field">
    <%= form.label :exercice_batch_id %>
    <%= form.text_field :exercice_batch_id %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_select :date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/test_executions/_git_error_badge.html.erb
<% if !test_execution.repository_working?%>
  <span class="badge badge-danger badge-pill">Git error: <%=repository_status_as_text(test_execution)%></span>
<% end %>

app/views/test_executions/_nothing_found_badge.html.erb
<% if !test_execution.sources_found? && test_execution.compile_success %>
  <% text = test_execution.comment ? test_execution.comment : "Folder exists, but no exercice found" %>
	<span class="badge badge-danger badge-pill" data-bs-toggle="tooltip" data-bs-placement="top" title="<%= text %>">Nothing found</span>
    <% group = test_execution.exercice_batch.exercice_groups.first %>
    <% if group and group.exercices.first%>
  		<%= link_to(find_exercice_code_exercice_path(group.exercices.first), data: {turbo: false}) do %>
  			<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-file-code" viewBox="0 0 16 16">
          <path d="M6.646 5.646a.5.5 0 1 1 .708.708L5.707 8l1.647 1.646a.5.5 0 0 1-.708.708l-2-2a.5.5 0 0 1 0-.708l2-2zm2.708 0a.5.5 0 1 0-.708.708L10.293 8 8.646 9.646a.5.5 0 0 0 .708.708l2-2a.5.5 0 0 0 0-.708l-2-2z"/>
          <path d="M2 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V2zm10-1H4a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1z"/>
        </svg>
  	<% end %>
  <% end %>
	
<% end %>

app/views/test_executions/_result_resumee.html.erb
<%= render partial: test_execution, layout: "test_executions/git_error_badge.html.erb" %>
<%= render partial: test_execution, layout: "test_executions/compile_badge.html.erb" %>
<%= render partial: test_execution, layout: "test_executions/nothing_found_badge.html.erb" %>

<% if test_execution.tests_available?%>
	<% if display_test_results? user, test_execution%>
		<%# return {total_count: total_count, not_found_count: not_found_count, failed_count: failed_count, correct_count: correct_count} %>
		<% resumee = test_execution.resumee %>
		<% aria_valuemax = resumee[:total_count] %>
		<% correct_count = resumee[:correct_count] %>
		<% failed_count = resumee[:failed_count] %>
		<% correct_percent = 100.0 * correct_count / resumee[:total_count] %>
		<% failed_percent = 100.0 * failed_count / resumee[:total_count] %>
		<%#= "#{aria_valuemax} #{correct_count} #{failed_count} #{correct_percent} #{failed_percent}"%>

		<div class="progress">
			<% if correct_count>0 %>
		  		<div class="progress-bar bg-success" role="progressbar" style="width: <%=correct_percent%>%" aria-valuenow="<%=correct_count%>" aria-valuemin="0" aria-valuemax="<%= aria_valuemax %>"><%=correct_count%></div>
		  	<% end %>
		  	<% if failed_count>0 %>
			  <div class="progress-bar bg-danger" role="progressbar" style="width: <%=failed_percent%>%" aria-valuenow="<%=failed_count%>" aria-valuemin="0" aria-valuemax="<%= aria_valuemax %>"><%=failed_count%></div>
			<% end %>
		</div>
	<% else %>
		<%= render partial: test_execution, layout: "test_executions/show_private_results" %>
	<% end %>
<% end %>

app/views/test_executions/_show_private_results.html.erb
<% resumee = test_execution.resumee %>
<% not_found_count = resumee[:not_found_count] %>
<% total_count = resumee[:total_count] %>
<% exercices_found = total_count - not_found_count %>

<%= t :private_results %>

<% if not_found_count == 0 %>
  <%= t :all_exercices_found %>
<% else %>
  <%= t :not_all_exercices_found, total: total_count, found: exercices_found %>
<% end %>

app/views/test_executions/_test_execution.html.erb
<td>
  <%= test_execution.exercice_batch.name %>
</td>

<td>
  <%= test_execution.date %>
</td>

<td><%= link_to 'Show', test_execution %></td>

app/views/test_executions/_test_execution_with_data.html.erb
<%= turbo_frame_tag test_execution do %>
  <p>
    <%= render partial: test_execution, layout: "test_executions/compile_badge" %>
    <%= render partial: test_execution, layout: "test_executions/nothing_found_badge" %>
  </p>

  <% if test_execution.comment %>
    <p><%= test_execution.comment %></p>
  <% end %>

  <p><%=link_to "test again", execute_tests_student_submission_path(test_execution.student_submission) %></p>
  <% if test_execution.test_report_file.attached? %>
    <p><%=link_to "View test xml report", url_for(test_execution.test_report_file) %></p>
  <% end %>



  <% if !test_execution.compile_success%>
    <div class="command_output"><%= simple_format(test_execution.command_output) %></div>
  <% end %>

  <% if !test_execution.folder_not_found %>
    <% @exercice_test_executions = test_execution.exercice_tests_executions.include_failures %>
    <% failures_count = @exercice_test_executions.count_failures %>
    <% if failures_count>0%>
      <% if display_test_results? current_user, test_execution %>
        <div class="div-table-striped">
          <% @exercice_test_executions.each do |exercice_tests_execution| %>
            <%= render exercice_tests_execution %>
          <% end %>
        </div>
      <% else %>
        <%= render partial: test_execution, layout: "test_executions/show_private_results" %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/test_executions/edit.html.erb
<h1>Editing Test Execution</h1>

<%= render 'form', test_execution: @test_execution %>

<%= link_to 'Show', @test_execution %> |
<%= link_to 'Back', test_executions_path %>

app/views/test_executions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Test Executions</h1>

<table>
  <thead>
    <tr>
      <th>Student</th>
      <th>Exercice batch</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @test_executions.each do |test_execution| %>
      <tr>
        <td><%= test_execution.student_submission.repository.git_url %></td>
        <td><%= test_execution.exercice_batch_id %></td>
        <td><%= test_execution.date %></td>
        <td><%= link_to 'Show', test_execution %></td>
        <td><%= link_to 'Edit', edit_test_execution_path(test_execution) %></td>
        <td><%= link_to 'Destroy', test_execution, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Test Execution', new_test_execution_path %>

app/views/test_executions/new.html.erb
<h1>New Test Execution</h1>

<%= render 'form', test_execution: @test_execution %>

<%= link_to 'Back', test_executions_path %>

app/views/test_executions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Student:</strong>
  <%= @test_execution.student_repository.student.username %>
</p>

<p>
  <strong>Exercice batch:</strong>
  <%= @test_execution.exercice_batch.name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @test_execution.date %>
</p>

<p>
  <strong>Compile success:</strong>
  <%= @test_execution.compile_success %>
</p>


<table class="table table-striped test_execution_result_table">
  <!--thead>
  </thead-->
  <tbody>
    <% @exercice_test_executions.each do |exercice_tests_execution| %>
      <tr>
        <%= render exercice_tests_execution %>
	  </tr>
	<% end %>
  </tbody>
</table>