config/routes.rb
Rails.application.routes.draw do
  #root :to => "students#index_with_results"
  root :to => "application#my_root"

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get 'users/sign_in', to: 'users/sessions#new', as: :new_user_session
    get 'users/sign_out', to: 'users/sessions#destroy', as: :destroy_user_session
  end

  get 'student_page', to: 'student_page#main'
  get 'student_page/results_for_batch', to: 'student_page#results_for_batch'

  resources :admins, only: [:index] do
    collection do
      get :update_gripau_data
      get :execute_all_tests
      get :import_students
      get :careful_gripau_console_page
      get :careful_upgrade_gripau
      get :careful_view_logs
      get :login_as
    end
  end
  

  resources :teachers do
    collection do
      get :update_gripau_data
    end
  end
  resources :exercice_groups
  resources :exercice_batches do
    collection do
      get :import
    end
    member do
      get :make_public
      get :student_results
      get :student_results_resumee
      get :execute_tests
      get :exercices_stats
      get :export_student_solutions
    end
  end

  resources :test_executions
  resources :test_case_executions do
    member do
      get :manual_accept
    end
  end
  resources :check_style_failures
  resources :test_failures
  resources :test_case_executions
  resources :exercice_tests_executions
  
  resources :student_repositories do
    member do
      get :validate
    end
  end

  resources :student_submissions do
    member do
      get :execute_tests
    end
    collection do
      get :import
      post :do_import
    end
  end

  resources :test_cases
  resources :exercices do
    member do
      get :find_exercice_code
    end
  end

  resources :students do 
    collection do
      get :index_with_results
      get :import
      post :do_import
      get :dashboard
    end
    member do 
      get :edit_git_url
      patch :update_git_url
      get :student_page
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/student_submission.rb
class StudentSubmission < ApplicationRecord
  include ActionView::RecordIdentifier

  has_many :test_executions
  belongs_to :test_execution, optional: true
  belongs_to :student
  belongs_to :exercice_batch
  belongs_to :student_repository

  has_one :teacher, through: :student
  scope :for_teacher, -> (teacher) { joins(:student).where("students.teacher_id = ?", teacher.id) }

  after_update_commit do
    broadcast_replace_to dom_id(student, "own_results_resumee"), partial: "student_submissions/results_resumee", locals: {student_submission: self, user: student.user}
  end

  def repository
    student_repository
  end

  def self.create_all_for(exercice_batch_id)
    exercice_batch = ExerciceBatch.find(exercice_batch_id)
    Student.all.each do |student|
      student_repository = StudentSubmission.find_or_initialize_by(student: student, exercice_batch: exercice_batch)
      student_repository.student_repository = student.default_repository
      student_repository.save!
    end
  end

end

app/controllers/student_submissions_controller.rb
class StudentSubmissionsController < ApplicationController
  before_action :teacher_required!, except: [:execute_tests]
  before_action :set_student_submission, only: [:show, :edit, :update, :destroy, :execute_tests]
  before_action :teacher_or_owner, only: [:execute_tests]

  def execute_tests
    ExecuteUserRepositoryTestJob.perform_later @student_submission, true
  end

  def import
    @exercice_batches = ExerciceBatch.all
  end

  def do_import
    StudentSubmission.import_csv(current_teacher, params[:exercice_batch_id], params[:file])
    redirect_to student_submissions_path, notice: "submissions imported"
  end

  # GET /student_submissions
  # GET /student_submissions.json
  def index
    @student_submissions = teacher_student_submissions
  end

  # GET /student_submissions/1
  # GET /student_submissions/1.json
  def show
  end

  # GET /student_submissions/new
  def new
    @student_submission = StudentSubmission.new
  end

  # GET /student_submissions/1/edit
  def edit
  end

  # POST /student_submissions
  # POST /student_submissions.json
  def create
    @student_submission = StudentSubmission.new(student_submission_params)

    respond_to do |format|
      if @student_submission.save
        format.html { redirect_to @student_submission, notice: 'Student repository was successfully created.' }
        format.json { render :show, status: :created, location: @student_submission }
      else
        format.html { render :new }
        format.json { render json: @student_submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /student_submissions/1
  # PATCH/PUT /student_submissions/1.json
  def update
    respond_to do |format|
      if @student_submission.update(student_submission_params)
        format.html { redirect_to @student_submission, notice: 'Student repository was successfully updated.' }
        format.json { render :show, status: :ok, location: @student_submission }
      else
        format.html { render :edit }
        format.json { render json: @student_submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /student_submissions/1
  # DELETE /student_submissions/1.json
  def destroy
    @student_submission.destroy
    respond_to do |format|
      format.html { redirect_to student_submissions_url, notice: 'Student repository was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student_submission
      @student_submission = StudentSubmission.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_submission_params
      params.require(:student_submission).permit(:student_id, :exercice_batch_id, :git_url)
    end

    def teacher_student_submissions
      StudentSubmission.for_teacher current_teacher
    end

    def teacher_or_owner
      if !current_teacher and current_student != @student_submission.student
        flash[:error] = "No tens permisos per aquesta acció."
        redirect_to destroy_user_session_path
      end
    end
end

app/views/student_submissions/_form.html.erb
<%= form_with(model: student_submissions, local: true) do |form| %>
  <% if student_submissions.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student_submissions.errors.count, "error") %> prohibited this student_submissions from being saved:</h2>

      <ul>
        <% student_submissions.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :student_id %>
    <%= form.text_field :student_id %>
  </div>

  <div class="field">
    <%= form.label :exercice_batch_id %>
    <%= form.text_field :exercice_batch_id %>
  </div>

  <div class="field">
    <%= form.label :student_submissions_id %>
    <%= form.text_field :student_submissions_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/student_submissions/_results_resumee.html.erb
<%= turbo_frame_tag dom_id(student_submission) do %>
  <div class="row p-3 border-bottom w-100">
    <div class="col-sm-3 exercice_batch_name">
      <%= student_submission.exercice_batch.name %>
    </div>
    <div class="col-sm-8">
      <% test_execution = student_submission.test_execution %>
      <% if test_execution %>
        <%= render partial: test_execution, layout: "test_executions/result_resumee", locals: {user: user}%>
      <% else %>
        <span class="badge badge-danger badge-pill">Never run</span>
      <% end %>
    </div>
    <div class="col-sm-1">
      <%= link_to "Re-Test", execute_tests_student_submission_path(student_submission) %>
    </div>
  </div>
<% end %>

app/views/student_submissions/_student_submission.html.erb
<td>
  <%= student_submission.exercice_batch.name %>
</td>

<td>
  <%= student_submission.repository.git_url %>
</td>
<td>
	<%= link_to 'Execute Test', execute_tests_student_submission_path(student_submission) %>
</td>

app/views/student_submissions/edit.html.erb
<h1>Editing Student Repository</h1>

<%= render 'form', student_submissions: @student_submissions %>

<%= link_to 'Show', @student_submissions %> |
<%= link_to 'Back', student_submissions_path %>

app/views/student_submissions/execute_tests.html.erb
<%= turbo_frame_tag dom_id(@student_submission) do %>
  <div class="row p-3 border-bottom w-100">
    <div class="col-sm-3 exercice_batch_name">
      <%= @student_submission.exercice_batch.name %>
    </div>
    <div class="col-sm-8 text-center">
      <%= image_tag("frog_eating_bug.gif", :alt => "waiting", height: "100px") %>
    </div>
    <div class="col-sm-1">
      Testing...
    </div>
  </div>
<% end %>

app/views/student_submissions/import.html.erb
<h1>Import CSV</h1>

Select CSV with 3 columns: student full name (may be empy), student email, git url


<%= form_tag do_import_student_submissions_path, multipart: true do %>
	<%= select_tag :exercice_batch_id,  options_from_collection_for_select(@exercice_batches, "id", "name")%><br>
	<%= file_field_tag :file %><br>
	<%= submit_tag "Import csv" %><br>
<% end %>

app/views/student_submissions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Student Repositories</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Student</th>
      <th>Exercice batch</th>
      <th>Git url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @student_submissions.each do |student_submissions| %>
      <tr>
        <td><%= student_submissions.student.email %></td>
        <td><%= student_submissions.exercice_batch.name %></td>
        <td><%= student_submissions.git_url %></td>
        <td><%= link_to 'Show', student_submissions %></td>
        <td><%= link_to 'Edit', edit_student_submissions_path(student_submissions) %></td>
        <td><%= link_to 'Destroy', student_submissions, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student Repository', new_student_submissions_path %>
<%= link_to 'Import Repositories', import_student_submissions_path %>

app/views/student_submissions/new.html.erb
<h1>New Student Repository</h1>

<%= render 'form', student_submissions: @student_submissions %>

<%= link_to 'Back', student_submissions_path %>

app/views/student_submissions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Student:</strong>
  <%= @student_submissions.student_id %>
</p>

<p>
  <strong>Exercice batch:</strong>
  <%= @student_submissions.exercice_batch_id %>
</p>

<p>
  <strong>Git url:</strong>
  <%= @student_submissions.repository.git_url %>
</p>

<%= link_to 'Edit', edit_student_submissions_path(@student_submissions) %> |
<%= link_to 'Back', student_submissions_path %>